

# ==============================================================
# KONFIGIRASYON SEV\u00c8
# ==============================================================
# Chanje p\u00f2 a pou evite er\u00e8 "Port 8080 already in use"
server.port=8085

# ==============================================================
# KONFIGIRASYON BAZ DE DONE (MySQL)
# ==============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/djoune_store?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=wees
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==============================================================
# KONFIGIRASYON MONCASH (API)
# ==============================================================
# Ranplase val\u00e8 sa yo ak vre kle ou jwenn nan MonCash Business la
moncash.client.id=VRE_CLIENT_ID_OU_A
moncash.client.secret=VRE_SECRET_OU_A

# S\u00e8vi ak 'sandbox' pou t\u00e8s, epi 'live' l\u00e8 magazen an prale sou ent\u00e8n\u00e8t tout bon
moncash.mode=sandbox












